---
title: "rollup"
execute: 
  enabled: false
---

## Description

The `rollup` function merges raw data with a rollup mapping table to establish hierarchical relationships. It identifies whether each record has a parent entity, adding a rollup status to the data.

```{python}
def rollup(raw_level_data, rollup_mapping , join_columns, parent_column):
    
    rolledup_data = pd.merge(raw_level_data, rollup_mapping, how='left', on=join_columns)
    
    rolledup_data['Rollup_Status'] = rolledup_data[parent_column].notna().replace({True: '1', False: '0'})
    
    return rolledup_data
```

## Input

1. **raw_level_data** (pandas.DataFrame):  
   The raw data at the most detailed level.

2. **rollup_mapping** (pandas.DataFrame):  
   A mapping table specifying parent-child relationships.

3. **join_columns** (list):  
   A list of column names used to join `raw_level_data` with the `rollup_mapping`.

4. **parent_column** (str):  
   The name of the column representing the parent in the rollup mapping.

## Output

- **rolledup_data** (pandas.DataFrame):  
  A DataFrame that includes all columns from the merged data along with a new column, `Rollup_Status`, which indicates whether a record has a parent (`1` for yes, `0` for no).

## See also

See [Roll-up_package](Roll-up_package.qmd).