---
title: "summarize"
execute: 
  enabled: false
---

## Description

In Module 1 we load the entire data at once as diagnosis datasets is relatively small. However if the dataset is large like lab data or ECG, the data points, we would need to use other methods. Below we define a custom summarzing function to summarize larger datasets. The function reads data in batches, summarized and further provides frequency of individual EHR elements

```{python}
def summarize(filepath, batch_size, dataframe=None):
    frequencies = {}
    non_null_records_count = {}
    total_records_count = 0

    for batch in pd.read_csv(filepath, chunksize=batch_size, dtype=str):

        total_records_count += batch.shape[0]

        for column in batch.columns:
            if column not in frequencies:
                frequencies[column] = {}
                non_null_records_count[column] = 0

            # Counting the number of non null records in each batch
            non_null_records_count[column] += batch[column].count()

            for item in batch[column]:
                if item in frequencies[column]:
                    frequencies[column][item] += 1
                else:
                    frequencies[column][item] = 1

    freq_table = [
        (column, len(frequencies[column]), non_null_records_count[column])
        for column in frequencies
    ]


    summary = pd.DataFrame(
            freq_table, columns=["Column_Name", "Unique_Values", "Non_Null_Records"]
        )
    

    return {'summary':summary,'freq':frequencies,'records':total_records_count}
```

## Input
The function accepts the following arguments:

1. **filepath** (str):  
   The path to the CSV file to be processed.

2. **batch_size** (int):  
   The number of rows to read at a time when processing the file in chunks. This helps handle large datasets efficiently.

3. **dataframe** (optional, default `None`):  
   Reserved for potential future use to allow passing a DataFrame directly. Currently, it has no effect on the function.

## Output
The function returns a dictionary containing the following keys:

1. **summary** (pandas.DataFrame):  
   A DataFrame summarizing the columns in the input file. It includes the following columns:
   - `Column_Name`: The name of each column in the dataset.
   - `Unique_Values`: The count of unique values in each column.
   - `Non_Null_Records`: The count of non-null records for each column.

2. **freq** (dict):  
   A nested dictionary where the keys are column names and the values are dictionaries mapping unique items in the column to their respective frequencies.

3. **records** (int):  
   The total number of records (rows) in the CSV file.


